version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      fontawesome:
        patterns:
          - "@fortawesome/*"
      octokit:
        patterns:
          - "@octokit/*"
      mui:
        patterns:
          - "@mui/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
