version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
      everything-else:
        patterns:
          - "*"
        exclude-patterns:
          - "react"
          - "react-*"
