name: GitHub Actions linting

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '.github/workflows/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/*.ya?ml'

concurrency:
  group: "action-lint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  workflow_syntax:
    permissions:
      contents: read
    name: Lint actions
    uses: move-agency/actions-templates/.github/workflows/actionlint.yml@main
  workflow_security:
    permissions:
      # required for workflows in private repositories
      contents: read
      actions: read
    name: Check action security
    uses: move-agency/actions-templates/.github/workflows/zizmor.yml@main
